[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"

[server]
head = """
<link rel="shortcut icon" href="https://raw.githubusercontent.com/tlinklater97/uber-go/main/favicon.png">
"""
