[gcp_service_account]
type = "service_account"
project_id = "ubergosync"
private_key_id = "13d16bd466a93f3d1135deba61d4bd0f849773d9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbw8XnqXhUuWCn
N5igHT14HwBMcSMWD0oolWU9ddehF5pawRA8KJmB7gLiKcSeZ1lfGS89m18BSJOB
SkcGrJLufJbI23fpPqIt2uEUxfObToN5eV4pg47N10wW4BbtbwR1EsCgzmyz7/64
uanlKBl7Wmz4vy32OJaUmImhM7S4CVvGVkUYOoebhY33n+KYIUNKFUqv1LwNTsZ7
O2bW14sTjK4GTbTPPm+U+XRpm6hAbVBUXNIIPBW+kOU0Ev45T2ek22JNBo27NGjW
oiTWuxdIBtMfYALuLcZev6JYx9zhv3flFMGSyBle/zNIPkXeiZ5dJ5+OwYb1nHDG
yzDPV3ErAgMBAAECggEAGFmJZYablfsIvfs188m+YznNbSW+i2NGf4OjOPFkDP3I
lmlZ5V2faa1QbBSFdRHI6dHhDattNaEn1e1LnyJ5MajuVWXhn+e3qJ1v1DSBuYST
jvjHHIxBVbJTZbwQOXvCYZ7V2A2M9rAMzMnRYk5bdWoUYOpaAASmnYIe+cFAfghR
79eCcvevOhSPaQ4WijaNYzzi8syVYY7TOebUHJMPukJmFEaG+wKrRWz1GZCqMH9f
CU6xHxVY4QoIndxCWRzWvESxsuwO4xpXKcqA98gv72zaI3j3x2nePfXFBlnaOkHP
K9AhxFeAXAsiz5LlcI6ziZq/VlJI2KU2zrIsVW7rcQKBgQDUc82j6fDZN0EyLrJ1
jclkdqEtdqnmYFi+5rded6J4rgpdU7gpf/bt+PmnCu4efAE/nugmB6+RTNkmOl0x
pHip51gKmzU0cECw9/71YDI3qCrkxbh85W8UOsI7PoXYjflbaJBAr7ni/rTD/vYz
1TKVQOg+km5egrXzMwIy9c582QKBgQC7sVnrjrzFKVN9JzgMtHU3UCLGMttrP8Jc
OHv8fhzmr1HhYpVDTnBBHQ41AZRIGGRhc9HQ0JXp6PYy+LBSVPC7drY+V3Fmgd6Y
znqJSXpQDeK9F1WIRgYYOFRiughuOQk3we0WgIWckAeyKS31NtbYhsNw2eauiPzx
eRLa06GrowKBgQCKpRwxeU0tZErOxfy+jI4+WtCqi8Mqzft8cbJ/GtHTsbif2S/Z
HWJ3QMEjyxVEnaZu73QOxXtE9oLL2NDSwcPhFVG2cj2RgCQnmWAwn9uFyOBdNc9E
6rHH4OS6pv3QKi7uAVoKbOOBiLlNIwlnIB4Hmzk1BHi0gtbc5I/t084yWQKBgAbz
Y2wYxh7bD+9zk1zNFgYtXoxOd9e57b2yjczk8rcMSRD6sKJkdj3DELKf01j0JkuB
mYSNJPAbo3pxwT3bTWrz033tiRKNvquUAe+xm+j5CquMAKviQ/mDpIRfdU53qEK7
WMdbjRcmMlLDuaL6G+y62OQF/cf65Lsgi7U03yjXAoGAUbLlCFbo4z0uVSujh7dh
Omjmhs1x9oOFV4uV7+l2CN0x/z7Fgaeyi+cEZX73NPnA90gBS/ig16+dgO0WMqa3
lAuO9vhvuFtsCuiHyyidvBWKpFbjZ6/SXGAu9b7GlopfwDOCM51/2sOw0JXS/wcx
Y9pHxnl/z+wSX7g6X9hpau4=
-----END PRIVATE KEY-----"""
client_email = "uber-go@ubergosync.iam.gserviceaccount.com"
client_id = "104135604997577920572"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/uber-go%40ubergosync.iam.gserviceaccount.com"
